# Generated by Django 5.0.2 on 2024-02-11 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='cars/img', verbose_name='Фотография')),
                ('petrol', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Бензин')),
                ('power', models.IntegerField(verbose_name='Мощность двигателя')),
                ('transmission', models.CharField(choices=[('автомат', 'Автомат'), ('механика', 'Механика')], default='механика', max_length=50, verbose_name='Коробка передач')),
                ('drive_unit', models.CharField(choices=[('переднеприводный', 'Переднеприводный'), ('заднеприводный', 'Заднеприводный'), ('полноприводный', 'Полноприводный')], default='переднеприводный', max_length=50, verbose_name='Привод')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='Пробег')),
                ('rudder', models.CharField(choices=[('левый', 'Левый'), ('правый', 'Правый')], default='левый', max_length=50, verbose_name='Руль')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='без_комплектации', max_length=50, verbose_name='Тип покупки')),
            ],
            options={
                'verbose_name': 'Тип комплектации',
                'verbose_name_plural': 'Типы комплектаций',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='Сообщения')),
                ('typing_date', models.DateField(auto_now=True, verbose_name='Дата отправления')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата отправления')),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cars', verbose_name='Машина')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
