# Generated by Django 5.0.2 on 2024-04-22 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCarsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_cars_id', models.ManyToManyField(blank=True, null=True, to='main.cars', verbose_name='Избранные машины')),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Лист избранных')),
            ],
            options={
                'verbose_name': 'Лист избранных',
                'verbose_name_plural': 'Листы избранных',
            },
        ),
    ]
