# Generated by Django 5.0.2 on 2024-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_favoritecarslist_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='drive_unit',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='rudder',
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет машины'),
        ),
        migrations.AddField(
            model_name='cars',
            name='equipment',
            field=models.CharField(choices=[('Комфорт', 'Левый'), ('Спорт', 'Правый'), ('Без комплектации', 'Правый')], default='Без комплектации', max_length=50, verbose_name='Комплектация'),
        ),
    ]
